/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_AHB1ENR (*(volatile uint32_t*)0x40023830)
#define RCC_APB1ENR (*(volatile uint32_t*)0x40023840)
#define GPIOA (*(volatile uint32_t*)0x40020000)
#define GPIOA_MODER (*(volatile uint32_t*)0x40020000) //GPIO with offset of 0x00
#define GPIOA_AFRL (*(volatile uint32_t*)0x40020020) //GPIOA with offset of 0x20
#define USART2_CR1 (*(volatile uint32_t*)0x4000440C) //USART2 enable
#define USART_BRR (*(volatile uint32_t*)0x40004408) //Set Baud rate of USART2
#define USART_DR (*(volatile uint32_t*)0x40004404) //Data register of UART
#define USART_SR (*(volatile uint32_t*)0x40004400) //Status register of UART

void enable_GPIOA_clock(void) {
	RCC_AHB1ENR |= 0x1;   // Set GPIOAEN bit
}

void enable_usart2_clock(void) {
    RCC_APB1ENR |= (1 << 17);   // Set USART2EN bit
}

void set_mode_alternate_function(void){
	GPIOA_MODER &= ~((0x3 << (2*2)) | (0x3 << (3*2))); // clear PA2 and PA3

	GPIOA_MODER |= (0x2 << (2*2)) | (0x2 << (3*2)); //PA2 and PA3 are used for alternate functions
}

void set_gpio_to_USART_mode(void){
	GPIOA_AFRL &= ~ ((0xF << (2*4)) | (0xF << (3*4))); //clear PA2 and PA3

	GPIOA_AFRL |= ((0x7 << (2*4)) | (0x7 << (3*4))); //set PA2 and PA3 to 0x7 to set USART2 communication on this pins
}

void enable_rx_tx_on_USART2(void){
	USART2_CR1 &= ~((1<<2) | (1<<3) | (1<<13)); //clear usart bits

	USART2_CR1 |= ((1<<2) | (1<<3) | (1<<13)); //set usart bits
}

void set_Baud_Rate(void){
	USART_BRR = 0x00; //clear baud rate register

	/*baud rate is 9600, clock is 42MHz, USART_DIV = 42x10^6/(16x9600) = 273.4375
	 * Mantissa bits [15:4] = 273 (0x111)
	 * Fraction bits [3:0] -> 0.4375x16 (over sampling by 16) = = 7 (0x7)
	 */
	USART_BRR = (0x111 << 4) | 0x7;
}

void usart2_tx(uint8_t data){
	//check if TXE bit is 1 ( Data is transferred to the shift register) it's 7th bit
	while(!(USART_SR & (1<<7)));
    USART_DR = data;
}

char usart2_rx(char *data){
	char status_uart = 0;
	/*RXNE: Read data register not empty, it's 5th bit of SR
	* 0: Data is not received
	* 1: Received data is ready to be read
	*/
	if(USART_SR & (1<<5)){
		*data = USART_DR;
	    status_uart |= 1<<5; // success
	}

	if(USART_SR & (1<<0)) status_uart |= 1;  //parity error
	if(USART_SR & (1<<1)) status_uart |= 1<<1;  //Framing error
	if(USART_SR & (1<<2)) status_uart |= 1<<2;  //Noise error
	if(USART_SR & (1<<3)) status_uart |= 1<<3;  //overrun error

	return status_uart;
}

int main(void)
{
	char data;
	enable_GPIOA_clock();
	enable_usart2_clock();
	set_mode_alternate_function();
	set_gpio_to_USART_mode();
	enable_rx_tx_on_USART2();
	set_Baud_Rate();

	usart2_tx('A');

    /* Loop forever */
	for(;;){
		uint8_t status = usart2_rx(&data);
		if(status & (1<<0)) usart2_tx('P'); //parity error
		if(status & (1<<1)) usart2_tx('F'); //Framing error
		if(status & (1<<2)) usart2_tx('N'); //Noise error
		if(status & (1<<3)) usart2_tx('O'); //overrun error
		if(status & (1<<5)) usart2_tx('S'); //success
	}
}
